### ISSUE TITLE
Fewer results are displayed when searching on a substring

### ISSUE THREAD

**Issue by codrutas1** [code4romania/ce-ma-fac#201]
I'm not sure which should be the logic of side-bar search on https://ce-ma-fac-dywwcem7c.now.sh/,
but when I search on "masuri" I obtain 5 results, and when I search on "masur" (which is a substring) I obtain fewer results (only 3).
My expectation would be vice-verse.
![Masuri vs masur](https://user-images.githubusercontent.com/6797637/79922382-899ea080-843c-11ea-92d6-1620bdffbf40.png)

**Comment by mihainsto** [comment]
I investigated the problem and it seems that in the two articles that are found in plus when searching "masuri", the word "masuri" is not present.

Fuse.js matches wrong the words.
In "Cum ne protejam?" Fuse.js matches the word "masuri" with "nasurile"
and In "Pentru cei care ofera ajutor" Fuse.js matches the word "masuri" with "Coșmaruri".

We can lower the threshold by 0.1 and get rid of those two results, but it is debatable because I think that with that lower threshold we may miss some misspelled words. And since the results are sorted based on the score I think that a few additional results won't affect anyone.

**Comment by codrutas1** [comment]
Seems reasonable, thank you for sharing the results.

**Comment by aniri** [comment]
Hey @mihainsto thanks for the investigation :smile: it seems to cover both this issue and #202 . I think we can leave the search as it is for now :smile: 

what do you thinnk @codrutas1 ?

**Comment by codrutas1** [comment]
I agree
